# experiment_config.yaml: settings related to the experiment being run when the run.py script is launched,
# any custom session variables you want displayed in a dialog for input at the start of the experiment

title: Visual search with eye tracking
code: ET_visual_search
version: '1.0'
description: Track gaze while searcing for a target.
session_defaults:
    name: Session Name
    code: E1S01
    comments: None
    user_variables:
        participant_age: 29
        participant_gender: Female
        glasses: No
        contacts: [Select, Yes, No ]
        eye_color: Unknown
session_variable_order: [ name, code, comments, participant_age, participant_gender, glasses, contacts, eye_color ]
ioHub:
    enable: True
    config: iohub_config.yaml

  
